<a href="https://colab.research.google.com/github/Kundan71/Python-numpy/blob/main/NumPy_Operations_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <u> Use only those concepts which have been taught till now </u>

In [ ]:
import numpy as np

# <u>**Problem 1**</u>

### What is the average value of the first 5 rows of the third and fourth columns?



In [ ]:
np.random.seed(21) # This guarantees the code will generate the same set of random numbers whenever executed
random_integers = np.random.randint(1,high=500000, size=(20, 5))
random_integers

array([[ 80842, 333008, 202553, 140037,  81969],
       [ 63857,  42105, 261540, 481981, 176739],
       [489984, 326386, 110795, 394863,  25024],
       [ 38317,  49982, 408830, 485118,  16119],
       [407675, 231729, 265455, 109413, 103399],
       [174677, 343356, 301717, 224120, 401101],
       [140473, 254634, 112262,  25063, 108262],
       [375059, 406983, 208947, 115641, 296685],
       [444899, 129585, 171318, 313094, 425041],
       [188411, 335140, 141681,  59641, 211420],
       [287650,   8973, 477425, 382803, 465168],
       [  3975,  32213, 160603, 275485, 388234],
       [246225,  56174, 244097,   9350, 496966],
       [225516, 273338,  73335, 283013, 212813],
       [ 38175, 282399, 318413, 337639, 379802],
       [198049, 101115, 419547, 260219, 325793],
       [148593, 425024, 348570, 117968, 107007],
       [ 52547, 180346, 178760, 305186, 262153],
       [ 11835, 449971, 494184, 472031, 353049],
       [476442,  35455, 191553, 384154,  29917]])

In [ ]:
# Your code here
avg_value = np.sum(random_integers[0:5,2:4])
print(avg_value)




2860585


#<u>**Problem 2**</u>

### In this problem, we are going to calculate distances between some pairs of points :

### <u> Measures of distances </u>
* ### Euclidean Distance : The distance between two points $(x_{1},y_{1})$ , $(x_{2},y_{2})$ is defined as :
${\displaystyle d(x,y)={\sqrt {(x_{1}-x_{2})^{2}+(y_{1}-y_{2})^{2}}}.}$

* ### Manhattan Distance : The distance between two points $(x_{1},y_{1})$ , $(x_{2},y_{2})$ is defined as :
${\displaystyle d(x,y)=|x_{1}-x_{2}|+|y_{1}-y_{2}|}$


### Create a 2-D array of 10 points where the x-coordinates and the y-coordinates can take random integral values between 5 and 20.


### Next, create two 1-D arrays(one for  Euclidean distance and the other for  Manhattan distance) for these points


In [ ]:
# Create the 10 points
import math
np.random.seed(21)
point1 = np.random.randint(5,20,size=(10))
point2 = np.random.randint(5,20,size=(10))
euclidean_dist = np.zeros((10,10))


2.0

In [ ]:
# Calculate Euclidean distances between these pairs of points (total 10*10 = 100 pairs including self pairs). This should give you a 10*10 2-D array where each value corresponds to the distance between a pair
for i in range(10):
  for j in range(10):
    dist = math.sqrt((point1[i]-point1[j])**2 + (point2[i]-point2[j])**2)
    euclidean_dist[i][j] = dist
print(euclidean_dist)





[[ 0.          2.23606798  6.40312424  9.21954446  9.48683298  3.16227766
   6.08276253  4.24264069  8.06225775  8.        ]
 [ 2.23606798  0.          7.21110255  8.94427191  9.43398113  5.
   5.09901951  6.40312424  6.32455532  7.28010989]
 [ 6.40312424  7.21110255  0.          4.47213595  4.12310563  4.12310563
   5.09901951  8.06225775  8.24621125  5.        ]
 [ 9.21954446  8.94427191  4.47213595  0.          1.          8.06225775
   4.24264069 12.04159458  6.32455532  2.23606798]
 [ 9.48683298  9.43398113  4.12310563  1.          0.          8.
   5.         12.          7.28010989  3.16227766]
 [ 3.16227766  5.          4.12310563  8.06225775  8.          0.
   6.40312424  4.          9.21954446  7.61577311]
 [ 6.08276253  5.09901951  5.09901951  4.24264069  5.          6.40312424
   0.          9.8488578   3.16227766  2.23606798]
 [ 4.24264069  6.40312424  8.06225775 12.04159458 12.          4.
   9.8488578   0.         12.20655562 11.40175425]
 [ 8.06225775  6.32455532  8.246

In [ ]:
# Calculate Manhattan distances between these pairs of points (total 10*10 = 100 pairs inlcuding self pairs).This should give you a 10*10 2-D array where each value corresponds to the distance between a pair.
manhattan_dist = np.zeros((10,10))
for i in range(10):
  for j in range(10):
    dist = abs(point1[i]-point1[j]) + abs(point2[i]-point2[j])
    manhattan_dist[i][j] = dist
print(manhattan_dist)




[[ 0.  3.  9. 11. 12.  4.  7.  6. 11.  8.]
 [ 3.  0. 10. 12. 13.  5.  6.  9.  8.  9.]
 [ 9. 10.  0.  6.  5.  5.  6.  9. 10.  7.]
 [11. 12.  6.  0.  1.  9.  6. 13.  8.  3.]
 [12. 13.  5.  1.  0.  8.  7. 12.  9.  4.]
 [ 4.  5.  5.  9.  8.  0.  9.  4. 13. 10.]
 [ 7.  6.  6.  6.  7.  9.  0. 13.  4.  3.]
 [ 6.  9.  9. 13. 12.  4. 13.  0. 17. 14.]
 [11.  8. 10.  8.  9. 13.  4. 17.  0.  5.]
 [ 8.  9.  7.  3.  4. 10.  3. 14.  5.  0.]]


## Find the closest pairs (excluding self pairs) on the basis of both the distance measures

In [ ]:
# Your code here





# <u>**Problem 3**</u>

## Extract all the contiguous 3x3 blocks from a random 10x10 matrix. For example, the first matrix corresponds to [:3,:3], then the second matrix corresponds to [:3,1:4],.... Once you have covered the first three rows, then the next set of matrices would be [1:4,:3],[1:4,1:4],.... and so on and so forth. The last matrix would be [7:10,7:10]

In [ ]:
# Your code below ..
np.random.seed(21)
matrix_2D = np.random.randint(5,20,size=(10,10))
for i in range(7):
  for j in range(7):
    #print(matrix_2D[i:i+3,j:j+3])
    pass









#<u>**Problem 4**</u>

### Write a function which finds the nearest value from a given value in an array of random N elements. Suppose you created an 1-D array with 15 elements taking values between 10 and 500. Your function would take any input from these values and return the nearest value. (You can use np.abs() function)

In [ ]:
# Your function below
import numpy as np
def find_nearest(array, value):
  array = np.asarray(array)
  idx = (np.abs(array - value)).argmin()
  # argmin() return indices of minimum element
  return array[idx]

array = np.random.randint(10,500,size=(15))
print(array)
print(find_nearest(array, 200))




[142 172  60 362 323 379 154 237  11 317  11  37 171 256  42]
172
